### ISSUE TITLE
The search does not include anything after &.

### ISSUE THREAD

**Issue by OutshineIssue** [Firefox0/Youtube-Lyrics#3]
_Great extension btw, I'm not as familiar with the code after the rewrite as I was with the previous one which was easier for a beginner like me, I'll be happy to contribute when I get better._

Anyway, I wanted to report that if there is an ampersand (&) in the title, the search omits what follows it.

**Comment by Firefox0** [comment]
Hello. Thanks for the compliment and the report.

I fixed the issue and overall improved the search.

I submitted the new version to the Firefox store.
